// web/src/components/organisms/Projects/ProjectLinks/index.svelte
<script lang="ts">
	import ProjectLink from '../../../molecules/Projects/ProjectLink/index.svelte';
</script>

<div class="project-links">
	<ProjectLink link={{ name: 'GitHub', icon: '/icons/social-medias/GitHub.png', url: '' }} />
	<ProjectLink link={{ name: 'Deploy', icon: '/icons/Deploy.png', url: '' }} />
</div>

<style>
	.project-links {
		display: flex;
		align-items: center;
		gap: 8px;

		margin-top: 8px;
	}
</style>

// web/src/components/tissues/Projects/ProjectLinks/index.tsx
import React from "react";
import ProjectLink from "../../../organisms/Projects/ProjectLink";

import GitHubIcon from "../../../../assets/icons/social-medias/GitHub.svg";
import WebIcon from "../../../../assets/icons/social-medias/Web.svg";

import { ProjectLinksProps } from "./types";

import { ProjectLinksContainer } from "./styles";

const ProjectLinks: React.FC<ProjectLinksProps> = ({
  gitHubUrl,
  deployUrl,
}): JSX.Element => {
  return (
    <ProjectLinksContainer>
      <ProjectLink
        name="GitHub"
        icon={GitHubIcon}
        url={gitHubUrl}
        backgroundColor="#000000"
      />
      <ProjectLink
        name="Deploy"
        icon={WebIcon}
        url={deployUrl}
        backgroundColor="#000000"
      />
    </ProjectLinksContainer>
  );
};

export default ProjectLinks;
