// web/src/components/molecules/Skills/Skill/index.svelte
<script lang="ts">
	import type { ISkill } from './types';

	export let skill: ISkill = {
		name: '',
		icon: '',
		website: ''
	};

	const { name, icon, website } = skill;
</script>

<button class="skill" on:click={() => window.open(website)} title={name}>
	<img src={icon} alt="" />
</button>

<style>
	.skill {
		display: flex;
		align-items: center;
		justify-content: center;

		height: 90px;
		width: 90px;

		border-radius: 16px;

		background: #1a1a1a;

		transition: all 150ms ease-in;
	}

	.skill:hover {
		transform: translateY(-7%);
	}

	.skill img {
		height: 50px;
	}
</style>

// web/src/components/Skill/index.tsx
import { MouseEvent } from "react";
import { ISkillProps } from "./types";

export function Skill({ skill: { name, icon, url } }: ISkillProps) {
  function openUrl(event: MouseEvent<HTMLAnchorElement>) {
    event.preventDefault();

    window.open(url);
  }

  return (
    <a
      href={url}
      title={name}
      onClick={openUrl}
      className="flex items-center justify-center bg-neutral-800 hover:bg-neutral-700 duration-300 size-[100px] rounded-3xl"
    >
      <img
        src={icon}
        alt={name}
        className="w-[60px] rounded-md pointer-events-none"
      />
    </a>
  );
}
