// web/src/components/tissues/About/SocialMedias/index.tsx
import React from "react";
import SocialMediaLink from "../../../organisms/About/SocialMediaLink";

import { SocialMediasContainer } from "./styles";

import MailIcon from "../../../../assets/icons/social-medias/Mail.svg";
import GitHubIcon from "../../../../assets/icons/social-medias/GitHub.svg";
import LinkedInIcon from "../../../../assets/icons/social-medias/LinkedIn.svg";

const SocialMedias: React.FC = (): JSX.Element => {
  return (
    <SocialMediasContainer className="social-media-links">
      <SocialMediaLink
        name="LinkedIn"
        icon={LinkedInIcon}
        url="https://www.linkedin.com/in/ricardobgx"
        background="#0077b5"
        openInANewWindow={true}
      />
      <SocialMediaLink
        name="GitHub"
        icon={GitHubIcon}
        url="https://github.com/ricardobgx"
        background="#000000"
        openInANewWindow={true}
      />
      <SocialMediaLink
        name="Email"
        icon={MailIcon}
        url="mailto:contato@ricardobrasileiro.com"
        background="#e59600"
      />
    </SocialMediasContainer>
  );
};

export default SocialMedias;

// web/src/components/molecules/Home/SocialMedias/index.svelte
<script lang="ts">
	import SocialMedia from '../../../atoms/Home/SocialMedia/index.svelte';
	import type { ISocialMedia } from '../../../atoms/Home/SocialMedia/types';

	const socialMedias: ISocialMedia[] = [
		{
			icon: '/icons/social-medias/LinkedIn.png',
			url: 'https://www.linkedin.com/in/ricardobgx'
		},
		{
			icon: '/icons/social-medias/GitHub.png',
			url: 'https://github.com/ricardobgx'
		},
		{
			icon: '/icons/social-medias/Mail.png',
			url: 'mailto:contato@ricardobrasileiro.com'
		}
	];
</script>

<div class="social-medias">
	{#each socialMedias as socialMedia}
		<SocialMedia bind:socialMedia />
	{/each}
</div>

<style>
	.social-medias {
		display: flex;
		align-items: center;
		gap: 2.5rem;
	}

	@media only screen and (min-width: 1100px) {
		.social-medias {
			position: absolute;

			bottom: 80px;
		}
	}
</style>
