// web/src/sections/Home/index.svelte
<script lang="ts">
	import Presentation from '../../components/tissues/Home/Presentation/index.svelte';
	import SocialMedias from '../../components/molecules/Home/SocialMedias/index.svelte';
</script>

<div id="home" class="section home">
	<Presentation />
	<SocialMedias />
</div>

<style>
	.home {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;

		width: 100%;

		position: relative;
	}

	@media only screen and (max-width: 1100px) {
		.home {
			gap: 5rem;
		}
	}
</style>

// src/components/Home.vue
<template>
  <div class="home my-section" id="home">
    <Profile />
    <Presentation />
  </div>
</template>

<script>
import Profile from "./Profile";
import Presentation from "./Presentation";

export default {
  name: "Home",
  components: {
    Profile,
    Presentation,
  },
};
</script>

<style>
#home {
  padding-top: 5rem;
}

.home {
  display: flex;
  justify-content: space-around;
  flex-wrap: wrap;
}

@media only screen and (max-width: 700px) {
  .home {
    justify-content: center;
  }
}
</style>
